version: '3.1'

services:
  database:
    container_name: nest-project
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: username # The PostgreSQL user (useful to connect to the database)
      POSTGRES_PASSWORD: password # The PostgreSQL password (useful to connect to the database)
      POSTGRES_DB: nestdb # The PostgreSQL default database (automatically created at first launch)
    ports:
      - 8000:5432
    volumes:
      - ./sql:/docker-entrypoint-initdb.d

  # Docker to run the NestJS application
  nestjs:
    container_name: nest-project-nestjs
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 3002:3000
    depends_on:
      - database
    environment:
      DATABASE_HOST: database # The host of the PostgreSQL database (the service name)
      DATABASE_PORT: 5432 # The port of the PostgreSQL database
      DATABASE_USER: username # The PostgreSQL user
      DATABASE_PASSWORD: password # The PostgreSQL password
      DATABASE_NAME: nestdb # The PostgreSQL database name
    command: npm run start:dev # Command to run the NestJS application in development mode
