version: '3.1'

services:
  database:
    container_name: nest-project
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: username # The PostgreSQL user (useful to connect to the database)
      POSTGRES_PASSWORD: password # The PostgreSQL password (useful to connect to the database)
      POSTGRES_DB: nestdb # The PostgreSQL default database (automatically created at first launch)
    ports:
      - 8000:5432
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
